### ISSUE TITLE
is:issue is:open very promising project - best one I have tried so far. 

### ISSUE THREAD

**Issue by BlockchainPunks** [Algo-Tradings/statistical-arbitrage-research#1]
Question: Do you have a project where a bot actually does the trades in real environment like binance or alpaca - I want to test this against actual exchange trading.

I do paper trading first so don't worry about the $

**Comment by Algo-Tradings** [comment]
Hello, friend. First, thank you for your comment!

Actually, I have a private bot running live! However, I have no intention of making it public at this moment.
